query GetFoodList {
    getFoodList {
        ok
        result {
            name
            calories
            proteins
            carbs
            fats
            ingredients {
                name
            }
            givenAmount
        }
        message
    }
}
