mutation EditFoodList($input: EditFoodListInputReal!) {
    editFoodList(input: $input) {
        ok
        result {
            name
            calories
            proteins
            carbs
            fats
            ingredients {
                name
                calories
                proteins
                carbs
                fats
            }
            givenAmount
        }
        message
    }
}
